import Head from 'next/head';
import Flex from '../components/flex';
import Card from '../components/card';
import Box from '../components/box';
import Discord from '../components/discord';
import Expnad from '../components/expnad';
import { getPosts } from '../services/post';

import SelectReact from '../components/reactSelect';
import StateComp from '../components/stateComp';

// import Image from 'next/image';
// import { Inter } from '@next/font/google';

interface Post {
  id: number;
  title: string;
  imgUrl: string;
}

interface Props {
  posts: Post[];
}

export default function Home({ posts }: Props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        {/* <Flex /> */}
        {/* <Card /> */}
        {/* <Box /> */}

        {/* <Discord /> */}
        {/* <Expnad cursorPointer /> */}
        {/* <SelectReact /> */}
        <StateComp />
      </main>
    </>
  );
}

export async function getStaticProps() {
  const posts = await getPosts();
  console.log(posts);
  return { props: { posts } };
}
